import React from "react";

export const metadata = {
  title: "General Layout",
  description: "Generated by create next app",
};

export default function GeneralLayout({ children }) {
  return (
    <>
      <div className="w-100 flex flex-col gap-2">
        <div className="bg-red-200">
          <strong>This Is general Layout</strong>
        </div>
        <div>{children}</div>
      </div>
    </>
  );
}
